### ISSUE TITLE
Ad not shown when custom UIViewController is really a UINavigationController

### ISSUE THREAD

**Issue by unpaq** [chrisjp/CJPAdController#20]
My app is using an instance of [SWRevealViewController](https://github.com/John-Lluch/SWRevealViewController) as the contentController. This is not working because it is not a UINavigationController.

I think this commit broke it for me:
https://github.com/chrisjp/CJPAdController/commit/78ae4f7c7998ca40896c8a0c2ec351465031f4ac

When `_isNavController` to `YES`, it works for me - so for now I have just modified your code.
I think it is impossible for you to recognize how to behave for custom UIViewControllers, but maybe you could add an override property, to force `_isNavController` or `_isTabBar` to `YES`...

**Comment by chrisjp** [comment]
Hi, I presume you fixed this yourself but I've finally got around to pushing an update which should handle it, by having an override property like we discussed.

I've added `overrideIsNavController`. If you set `[CJPAdController sharedInstance].overrideIsNavController = YES` in your app delegate then CJPAdController should handle your VC as if it were a UINavigationController, which should hopefully be a good fix for cases like yours!

I'll be pushing it in just a second, but let me know if it doesn't work for you, it may be that it's too hard to predict how it can work in all possible implementations of view controllers.
