### ISSUE TITLE
Removed banner still shows up if canceled before initialDelay time passed

### ISSUE THREAD

**Issue by pawelkata** [chrisjp/CJPAdController#21]
Hello,

A case:
1. Setup CJPAdController with initialDelay of 60 seconds.
2. Remove the banner before 60 seconds passed.
3. The banner will still show up, as it's creation is scheduled.

Solution:

Add this one line below code to removeAdsAndMakePermanent:andRemember:, at the beginning of the method:
```
[NSObject cancelPreviousPerformRequestsWithTarget:self];
```

Cheers and thanks for a great lib!

**Comment by chrisjp** [comment]
Good catch, will get that fixed up later, thanks!
